version: '3.8'

networks:
  loki:

services:
  loki:
    image: grafana/loki:main
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-local-config.yaml:/mnt/config/loki-local-config.yaml
    command: -config.file=/mnt/config/loki-local-config.yaml
    networks:
      - loki

  grafana:
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    image: grafana/grafana:main-ubuntu
    ports:
      - "3000:3000"
    networks:
      - loki
